name             'sinatra-ssl-spike'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures handson'
long_description 'Installs/Configures handson'
version          '0.1.0'
depends          'chef-dk'
depends          'docker'
depends          'curl'
